app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_category:
    type: rest
    resource: AppBundle\Controller\CategoryController
    prefix:   /api
    options:
        expose: true

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc