app:
    resource: "@AppBundle/Controller/web/"
    type:     annotation

app_category:
    type: rest
    resource: AppBundle\Controller\CategoryController
    prefix:   /api
    options:
        expose: true

app_issue:
    type: rest
    resource: AppBundle\Controller\IssueController
    prefix:   /api
    options:
        expose: true

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/v1