parameters:
    # Document Class
    app.document.category: AppBundle\Document\Category
    app.document.issue: AppBundle\Document\Issue

    # Handler Class
    app.category.handler: AppBundle\Handler\CategoryHandler
    app.issue.handler: AppBundle\Handler\IssueHandler

    # FormType Class
    app.form.type.category: AppBundle\Form\Type\CategoryType
    app.form.type.issue: AppBundle\Form\Type\IssueType

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.document_manager:
        abstract: true
        calls:
            - [ setDocumentManager, [ "@doctrine.odm.mongodb.document_manager" ] ]
            - [ setFormFactory, [ "@form.factory" ] ]

    app.handler.category:
        class: "%app.category.handler%"
        parent: app.document_manager
        arguments: [ "%app.document.category%", "%app.form.type.category%" ]

    app.handler.issue:
        class: "%app.issue.handler%"
        parent: app.document_manager
        arguments: [ "%app.document.issue%", "%app.form.type.issue%" ]
