<?php

namespace AppBundle\Document\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends DocumentRepository
{
    public function findAllCountIssues()
    {
        $dm = $this->getDocumentManager();

        $categories = $dm->createQueryBuilder('AppBundle:Category')
            ->select('id', 'name')
            ->group(array('issues'), array('count'=>0))
            ->reduce('function (obj, prev) { prev.count += 1;}')
            ->getQuery();

        return $categories->execute();

    }
}