<?php

namespace AppBundle\Document\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends DocumentRepository
{
    public function findAllByCategory($category)
    {
        $dm = $this->getDocumentManager();

        $issues = $dm->createQueryBuilder('AppBundle:Issue')
            ->field('category.id')->equals($category)
            ->getQuery();

        return $issues->execute();
    }
}